(ns client.app)
(defn greet [] (println "hello lumo"))
(defn add [a b] (+ a b))
(greet)
(when (number? 12)
      (println "yes"))
(if (string? "hello")
  (println "yes")
  (println "no"))

(defn ^:export main [] (greet))
(def a 1)
(def a 2)
;(println "can I use class?")
;(println (str "class of 1 is: " (class 1)))
;(println "I can use class")
;(println (eval '(+ 1 2)))
(coll? '(1 2 3))
(coll? [1 2 3])
(seq? '(1 2 3))
(seq? [1 2 3])
(println  (take 4 (range)))
(let [p (.createElement js/document "p")]
     (set! (.-textContent p) "hello lumo")
     (.appendChild js/document.body p))
